version: '3'

dotenv:
- .env
- packages/.env

vars:
    DRY: ""
    SKIP: ""
    FLAGS: ""

tasks:
    default: task -l

    build:venv:
        requires: { vars: [A] }
        cmds:
        -   >
            bash util/build-venv.sh 
            $(pwd)/packages/{{.A}}/requirements.txt
            $(pwd)/packages/{{.A}}.zip
        - task: build:action
        sources:
        - "packages/{{.A}}/requirements.txt"
        generates:
        - "packages/{{.A}}.zip"


    build:node:
        requires: { vars: [A] }
        cmds:
        -   >
            bash util/build-node.sh 
            $(pwd)/packages/{{.A}}/package.json
            $(pwd)/packages/{{.A}}.zip
        - task: build:action
        sources:
        - "packages/{{.A}}/package.json"
        generates:
        - "packages/{{.A}}.zip"



    build:zip:
        requires: { vars: [A] }
        cmds:
        -   |
            if test -e "packages/{{.A}}/package.json"
            then echo "*** building nodejs deployment"
                task build:node A="{{.A}}"
            fi
            if test -e "packages/{{.A}}/requirements.txt"
            then echo "*** building python deployment" 
                task build:venv A="{{.A}}"
            fi

    build:action:
        aliases: [b]
        requires: { vars: [A] }
        cmds:
        - task: build:zip
        -   |
            FILE=$(basename "{{.A}}")
            cd packages/{{.A}}
            zip ../$FILE.zip  * -x requirements.txt
        sources:
        - packages/{{.A}}/*
        generates:
        - packages/{{.A}}.zip

    clean:
        ignore_error: true
        cmds:
        - rm -v packages/*/*.zip

    setup: 
        desc: setup Nuvolaris MastroGPT
        cmds:
        - |
            nuv -version
            for i in packages/*/*/requirements.txt
            do pip install -r $i
            done
            task config

    cli:
        desc: python cli
        cmds:
        - |
            ipython -i util/init.ipy
    
    serve:
        desc: local web server
        aliases: [s]
        ignore_error: true
        cmds:
        - bash util/http-serve.sh 
        - echo "Terminated or another server started..."


    single:
        desc: deploy a single action (either a file or a directory)
        requires: {vars: [A]}
        cmds:
        - python -m util.deploy -s "{{.A}}"
        
    deploy:
        desc: deploy actions
        cmds:
        - python -m util.deploy {{.FLAGS}}
        - nuv web upload web
        - echo "Deployed on:" "$NUVDEV_HOST"

    undeploy:
        ignore_error: true
        desc: undeploy actions
        cmds:
        - task: clean
        - >
            nuv action list | awk 'NR>1 t{ print $1}' | xargs -L1 -r nuv action delete
        - >
            nuv package list | awk 'NR>1 t{ print $1}' | xargs -L1 -r nuv package delete

    devel:
        desc: incremental interactive development mode
        cmds:
        - task: undeploy
        - python -m util.deploy -w {{.FLAGS}}

        
    config:
        desc: configure MastroGPT to access nuvolaris.dev
        silent: true
        cmds:
        -   |
            clear
            while ! test -e ~/.wskprops.v2
            do
                echo "*** Configuring Access to nuvolaris.dev with Azure OpenAI ***"
                echo -n "Enter Username: "
                read NUVDEV_USERNAME
                if nuv -login https://nuvolaris.dev "$NUVDEV_USERNAME"
                then
                    echo "## DO NOT EDIT - GENERATED BY task config" >.env
                    echo "## PUT YOUR SECRETS IN packages/.env OR as Codespace Secrets" >>.env
                    echo "## https://docs.github.com/en/codespaces/managing-your-codespaces/managing-your-account-specific-secrets-for-github-codespaces" >>.env
                    echo ""
                    source ~/.wskprops
                    echo "NUVDEV_USERNAME=$NUVDEV_USERNAME" >>.env
                    echo "NUVDEV_HOST=https://$NUVDEV_USERNAME.nuvolaris.dev" >>.env
                    echo "OPENAI_API_HOST=https://openai.nuvolaris.io" >>.env
                    echo "$AUTH" | awk -F: '{print "OPENAI_API_KEY=" $1 }' >>.env
                    nuv -config -d >>.env
                    touch ~/.wskprops.v2
                fi
            done
            echo "**************************************************************************************"
            echo "*** Type 'deploy' to deploy your app to https://$NUVDEV_USERNAME.nuvolaris.dev"
            echo "*** Type 'devel'  to start incremental development mode"
            echo "**************************************************************************************"

    build_web:
      desc: execute npm run build and extract data to web folder
      cmds:
        - cd ./svelte-waitlist && npm run build && cp -r build/* ../web/
        - nuv web upload web
        - echo "Deployed on:" "$NUVDEV_HOST"
