version: '3'

dotenv:
- .env

vars:
  IMG: "ghcr.io/nuvolaris/mastrogpt-starter"
  VER: "3.1.0-mastrogpt"
  TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo latest

tasks:

  build-and-push:
    - test -e .env
    - docker login ghcr.io -u "$GITHUB_USER" -p "$GITHUB_TOKEN"
    - docker build  -t {{.IMG}}:{{.TAG}} . --push

  buildx-and-push:
    - test -e .env
    - docker login ghcr.io -u "$GITHUB_USER" -p "$GITHUB_TOKEN"
    - docker buildx create --use
    - docker run -it --rm --privileged tonistiigi/binfmt --install all
    - docker buildx build --platform linux/amd64,linux/arm64 --no-cache  -t {{.IMG}}:{{.TAG}} . --push

  image-tag:
    silent: true
    cmds:
    - git tag -d $(git tag) 
    - git tag -f {{.VER}}.$(date +%y%m%d%H%M)
    - env PAGER= git tag